---
title: "Minneapolis 2021 Election - Question 2 Project"
author: "Luke Kolar"
date: "12/12/2021"
output: html_document
---

```{r, message = F, warning = F}

# Helpful libraries
library(sf)
library(rgdal)
library(janitor)
library(readxl)
library(RColorBrewer)
library(viridis)
library(scales)
library(gridExtra)
library(cowplot)
library(rlang)
library(readxl)
library(stargazer)

# Load important libraries last
library(shapefiles)
library(tidyverse)

```

```{r, message = F, warning = F}

# Read Hennepin County precinct map
hennepin_precincts_raw <- readOGR( 
  dsn = paste0(getwd(),"/data/hennepin_precincts/"), 
  layer = "Voting_Precincts",
  verbose = FALSE) 

# Transform file to sf format
hennepin_precincts_messy <- spTransform(hennepin_precincts_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
hennepin_precincts_sf <- st_as_sf(hennepin_precincts_messy)

# Clean data - merging empty precincts
mpls_precincts <- hennepin_precincts_sf %>%
  clean_names() %>% 
  filter(munic_name == "MINNEAPOLIS") %>% 
  mutate(precinct_name = paste0("W-", ward, " P-", precinct)) %>%
  mutate(precinct_name = ifelse(precinct_name == "W-10 P-5-B", "W-10 P-5-A", precinct_name)) %>% 
  mutate(precinct_name = ifelse(precinct_name == "W-10 P-3-B", "W-10 P-3-A", precinct_name)) %>% 
  group_by(precinct_name) %>%
  summarise(geometry = st_union(geometry)) %>%
  ungroup() %>% 
  mutate(precinct_name = ifelse(precinct_name == "W-10 P-5-A", "W-10 P-5", precinct_name)) %>% 
  mutate(precinct_name = ifelse(precinct_name == "W-10 P-3-A", "W-10 P-3", precinct_name))

```

```{r, message = F, warning = F}

# Load / clean demographic data and election returns from Excel
precinct_info <- read_xlsx("data/precinct_info.xlsx", col_names = TRUE) %>% 
  clean_names() %>% 
  select(!ward) %>% 
  select(!precinct)

```

```{r, message = F, warning = F}

# Read Hennepin County precinct map
mpls_shots_fired_raw <- readOGR( 
  dsn = paste0(getwd(),"/data/mpls_shots_fired/"), 
  layer = "Shots_Fired",
  verbose = FALSE) 

# Transform file to st format, then to sf format
mpls_shots_fired_messy <- spTransform(mpls_shots_fired_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
mpls_shots_fired_sf <- st_as_sf(mpls_shots_fired_messy)

# Clean data - merging empty precincts
locations_draft <- mpls_shots_fired_sf %>% 
  clean_names() %>%
  as.data.frame() %>% 
  filter(str_detect(year, "2021"))

locations_mapped <- st_as_sf(locations_draft, coords = c('latitude', 'longitude'), 
                             crs = st_crs(mpls_precincts))

locations_only <- locations_draft %>% 
  mutate(intersection = as.integer(st_intersects(geometry, mpls_precincts)), 
         area = if_else(is.na(intersection), '', mpls_precincts$precinct_name[intersection])) 

# Create number of gunshots, number of summer gunshots columns
locations <- locations_only %>% 
  group_by(area) %>% 
  summarize(n_shots = n()) %>% 
  ungroup() %>% 
  filter(!area == "") %>% 
  full_join(locations_only %>% 
              filter(month %in% c(6, 7, 8)) %>% 
              group_by(area) %>% 
              summarize(n_shots_summer = n()) %>% 
              ungroup() %>% 
              filter(!area == ""), 
            by = c("area"))

# Join precinct shapefiles with demographic and gunshot data
mpls_precincts_shots <- mpls_precincts %>% 
  full_join(locations, by = c("precinct_name" = "area")) %>% 
  full_join(precinct_info, by = c("precinct_name" = "name")) %>% 
  mutate(n_shots = ifelse(is.na(n_shots), 0, n_shots),
         n_shots_summer = ifelse(is.na(n_shots_summer), 0, n_shots_summer)) %>% 
  mutate(perc_voted_no = 100*votes_no/(votes_yes + votes_no),
         precinct_area_m2 = as.numeric(st_area(geometry)),
         n_shots_by_m2 = n_shots/precinct_area_m2,
         n_shots_by_m2_summer = n_shots_summer/precinct_area_m2,
         turnout = 100*(votes_yes + votes_no)/vap_pop,
         log_n_shots_summer = ifelse(n_shots_summer == 0, 0, log(n_shots_summer)))

# /// saveRDS(mpls_precincts_shots, file = "data/mpls_precincts_shots.rds")

```

```{r, message = F, warning = F}

## MAP COLLECTION:

# Showing out-of-jurisdiction gunshots that were excluded from the final data
mpls_precincts %>% 
  ggplot(.) + geom_sf() + 
  geom_point(data = locations_only %>% filter(area == ""), 
             aes(x = longitude, y = latitude), size = 3, shape = 23, fill = "darkred") + 
  theme_void()

# Mapping gunshots over the course of 2021 in its entirety
mpls_precincts %>% 
  ggplot(.) + geom_sf() + 
  geom_point(data = locations_only %>% filter(!area == ""), 
             aes(x = longitude, y = latitude), size = 0.5, shape = 20, color = "darkred") + 
  theme_void()

# Mapping gunshots during the summer of 2021
mpls_precincts %>% 
  ggplot(.) + geom_sf() + 
  geom_point(data = locations_only %>% filter(month %in% c(6, 7, 8), !area == ""), 
             aes(x = longitude, y = latitude), size = 0.5, shape = 20, color = "darkred") + 
  theme_void()

# Summer 2021 gunshot heat map by precinct
mpls_precincts_shots %>% 
  ggplot(.) + geom_sf(aes(fill = n_shots_summer)) + 
  scale_fill_viridis_c(#low = "white", high = "red", na.value = NA,
                      guide = guide_colorbar(frame.colour = "black", ticks.colour = "black")) + 
  theme_void() + 
  labs(fill = "Summer gunshots")

# Mapping gunshots over precinct % Black
mpls_precincts_shots %>% 
  ggplot(.) + geom_sf(aes(fill = perc_black), color = "white") + 
  geom_point(data = locations_only %>% filter(month %in% c(6, 7, 8), !area == ""), 
             aes(x = longitude, y = latitude), size = 0.75, shape = 20, color = "red3") + 
  scale_fill_gradient(low = "#CEB5C9", high = "#1B1318", na.value = NA,
                      guide = guide_colorbar(frame.colour = "white", ticks.colour = "white")) + 
  theme_void() + 
  labs(fill = "% Black")

# Mapping gunshots over precinct % non-white
mpls_precincts_shots %>% 
  ggplot(.) + geom_sf(aes(fill = 100 - perc_white), color = "white") + 
  geom_point(data = locations_only %>% filter(month %in% c(6, 7, 8), !area == ""), 
             aes(x = longitude, y = latitude), size = 0.75, shape = 20, color = "red3") + 
  scale_fill_gradient(low = "#CEB5C9", high = "#1B1318", na.value = NA,
                      guide = guide_colorbar(frame.colour = "white", ticks.colour = "white")) + 
  theme_void() + 
  labs(fill = "% Non-white", title = "Summer gunshots and precinct % non-white",
       caption = " ") + 
  theme(plot.title = element_text(size = 16),
        plot.caption = element_text(vjust = 6, hjust = 1.5, size = 10))

# \\\ ggsave("images/fig3.png")

# Mapping gunshots over precinct % voted "NO" on anti-police ballot initiative
mpls_precincts_shots %>% 
  ggplot(.) + geom_sf(aes(fill = votes_no/(votes_yes + votes_no)), color = "white") + 
  geom_point(data = locations_only %>% filter(month %in% c(6, 7, 8), !area == ""), 
             aes(x = longitude, y = latitude), size = 0.75, shape = 20, color = "red3") + 
  scale_fill_gradient(low = "#CEB5C9", high = "#1B1318", na.value = NA,
                      guide = guide_colorbar(frame.colour = "white", ticks.colour = "white")) + 
  theme_void() + 
  labs(fill = "% voted no", title = "Summer gunshots and precinct % voted \"no\" on Q2",
       caption = "One red dot = one gunshot") + 
  theme(plot.title = element_text(size = 16),
        plot.caption = element_text(vjust = 6, hjust = 1.5, size = 10))

# \\\ ggsave("images/fig4.png")

# Mapping gunshots over voter turnout 
mpls_precincts_shots %>% 
  ggplot(.) + geom_sf(aes(fill = turnout), color = "white") + 
  geom_point(data = locations_only %>% filter(month %in% c(6, 7, 8), !area == ""), 
             aes(x = longitude, y = latitude), size = 0.75, shape = 20, color = "red3") + 
  scale_fill_gradient(low = "#CEB5C9", high = "#1B1318", na.value = NA,
                      guide = guide_colorbar(frame.colour = "white", ticks.colour = "white")) + 
  theme_void() + 
  labs(fill = "Voter turnout") + 
  theme(legend.text = element_text(size = 11),
        legend.title = element_text(size = 12))

# /// ggsave("images/c7.png")

```

```{r, message = F, warning = F}

# Analyzing % voted "NO" variable
mpls_precincts_shots %>% 
  ggplot(aes(x = perc_voted_no)) + geom_density() + theme_minimal() + 
  labs(x = "% voted \"no\" on Q2", y = "Density") + 
  theme(axis.title = element_text(size = 15))

# /// ggsave("images/b1.png")

mpls_precincts_shots %>% 
  arrange(perc_voted_no) %>% 
  as.data.frame() %>% 
  select(precinct_name, perc_voted_no) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  arrange(desc(perc_voted_no)) %>% 
  as.data.frame() %>% 
  select(precinct_name, perc_voted_no) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  as.data.frame() %>% 
  summarize(mean = mean(perc_voted_no))

```


```{r, message = F, warning = F}

# Analyzing turnout variable
mpls_precincts_shots %>% 
  ggplot(aes(x = turnout)) + geom_density() + theme_minimal() + 
  labs(x = "% turnout on Q2 vote", y = "Density") + 
  theme(axis.title = element_text(size = 15))

# /// ggsave("images/b2.png")

# Turnout simple regression models with variables
stargazer(lm(turnout ~ log_n_shots_summer, data = mpls_precincts_shots %>% 
                    mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
                    mutate(log_n_shots_summer = log(n_shots_summer))), type = "html",
          out = "images/b3.html",
          covariate.labels = c("Log summer gunshots"),
          dep.var.labels   = "% turnout on Q2")

stargazer(lm(perc_voted_no ~ turnout, data = mpls_precincts_shots), type = "html",
          out = "images/b4.html",
          covariate.labels = c("% turnout on Q2"),
          dep.var.labels   = "% voted \"no\" on Question 2")

stargazer(lm(turnout ~ perc_white, data = mpls_precincts_shots), type = "html",
          out = "images/b5.html",
          covariate.labels = c("Voting age % white"),
          dep.var.labels   = "% turnout on Q2")

```


```{r, message = F, warning = F}

# Turnout scatterplots with variables
mpls_precincts_shots %>% 
  ggplot(aes(x = turnout, y = perc_voted_no)) + geom_point() + geom_smooth(method = "lm")

mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  ggplot(aes(x = log_n_shots_summer, y = turnout)) + geom_point() + geom_smooth(method = "lm")

mpls_precincts_shots %>% 
  ggplot(aes(x = n_shots_summer, y = turnout)) + geom_point() + geom_smooth(method = "lm")

mpls_precincts_shots %>% 
  ggplot(aes(x = vap_perc_white, y = turnout)) + geom_point() + geom_smooth(method = "lm") + theme_minimal() + 
  labs(x = "Voting age % white", y = "% turnout") + 
  theme(axis.title = element_text(size = 15))

# /// ggsave("images/c8.png")

# Variable statistics
mpls_precincts_shots %>% 
  mutate(turnout = 100*(votes_yes + votes_no)/vap_pop) %>% 
  arrange(turnout) %>% 
  as.data.frame() %>% 
  select(precinct_name, turnout) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>%
  mutate(turnout = 100*(votes_yes + votes_no)/vap_pop) %>% 
  arrange(desc(turnout)) %>% 
  as.data.frame() %>% 
  select(precinct_name, turnout) %>% 
  filter(row_number() %in% c(1))

mpls_precincts_shots %>% 
  mutate(turnout = 100*(votes_yes + votes_no)/vap_pop) %>% 
  as.data.frame() %>% 
  summarize(mean = mean(turnout))

```


```{r, message = F, warning = F}

# Analyzing voting age population variable
mpls_precincts_shots %>% 
  ggplot(aes(x = vap_pop)) + geom_density() + theme_minimal() + 
  labs(x = "Voting age population", y = "Density") + 
  theme(axis.title = element_text(size = 15))

# /// ggsave("images/b6.png")

mpls_precincts_shots %>% 
  arrange(vap_pop) %>% 
  as.data.frame() %>% 
  select(precinct_name, vap_pop) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  arrange(desc(vap_pop)) %>% 
  as.data.frame() %>% 
  select(precinct_name, vap_pop) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  as.data.frame() %>% 
  summarize(mean = mean(perc_voted_no))

```

```{r, message = F, warning = F}

# Analyzing voting age population % white variable
mpls_precincts_shots %>% 
  ggplot(aes(x = vap_perc_white)) + geom_density() + theme_minimal() + 
  labs(x = "Voting age population % white", y = "Density") + 
  theme(axis.title = element_text(size = 15))

# /// ggsave("images/b7.png")

mpls_precincts_shots %>% 
  arrange(vap_perc_white) %>% 
  as.data.frame() %>% 
  select(precinct_name, vap_perc_white) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  arrange(desc(vap_perc_white)) %>% 
  as.data.frame() %>% 
  select(precinct_name, vap_perc_white) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  as.data.frame() %>% 
  summarize(mean = mean(vap_perc_white))

```

```{r, message = F, warning = F}

# Comparing raw and log gunshot variables
mpls_precincts_shots %>% 
  ggplot(aes(x = n_shots_summer)) + geom_density() + theme_minimal() + 
  labs(x = "Count of summer gunshots by precinct", y = "Density", 
       title = "Density plot of summer gunshots by precinct") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.title = element_text(size = 13))

# /// ggsave("images/fig1.png")

mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  ggplot(aes(x = log_n_shots_summer)) + geom_density() + theme_minimal() + 
  labs(x = "Log count of summer gunshots", y = "Density", 
       title = "Density plot of log summer gunshots by precinct") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.title = element_text(size = 13))

# /// ggsave("images/fig2.png")

mpls_precincts_shots %>% 
  arrange(n_shots_summer) %>% 
  as.data.frame() %>% 
  select(precinct_name, n_shots_summer) %>% 
  filter(row_number() %in% c(1:30))

mpls_precincts_shots %>% 
  arrange(desc(n_shots_summer)) %>% 
  as.data.frame() %>% 
  select(precinct_name, n_shots_summer) %>% 
  filter(row_number() %in% c(1:20))

mpls_precincts_shots %>% 
  as.data.frame() %>% 
  summarize(mean = mean(n_shots_summer))

```

```{r, message = F, warning = F}

# Analyzing log gunshot variable
mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  ggplot(aes(x = log_n_shots_summer)) + geom_density() + theme_minimal() + 
  labs(x = "Log count of summer gunshots", y = "Density", 
       title = "Density plot of log summer gunshots by precinct") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.title = element_text(size = 13))

mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  arrange(log_n_shots_summer) %>% 
  as.data.frame() %>% 
  select(precinct_name, log_n_shots_summer) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  arrange(desc(log_n_shots_summer)) %>% 
  as.data.frame() %>% 
  select(precinct_name, log_n_shots_summer) %>% 
  filter(row_number() %in% c(1:10))

mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  as.data.frame() %>% 
  summarize(mean = mean(log_n_shots_summer))

```

```{r, message = F, warning = F}

# Scatterplot of voting age population white and % voted "NO" on anti-police ballot initiative
mpls_precincts_shots %>% 
  filter(!is.na(precinct_name)) %>% 
  ggplot(aes(x = vap_perc_white, y = perc_voted_no)) + geom_point() + 
  geom_smooth(method = "lm") + theme_minimal() + 
  labs(y = "% voted \"no\"", x = "Voting age population % white",
       title = "Precinct voting age population % white and % voting \"no\" on Q2") + 
  ylim(20, 85) + theme(plot.title = element_text(size = 16))

# /// ggsave("images/fig5.png")

# Scatterplot of log summer gunshots and % voted "NO" on anti-police ballot initiative
mpls_precincts_shots %>% 
  mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
  mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
  ggplot(aes(x = log_n_shots_summer, y = perc_voted_no)) + geom_point() + 
  geom_smooth(method = "lm") + theme_minimal() + 
  labs(y = "", x = "Log count of summer 2021 gunshots",
       title = "Precinct log summer gunshots and % voting \"no\" on Q2") + 
  ylim(20, 85) + theme(plot.title = element_text(size = 16))

# /// ggsave("images/fig6.png")

```


```{r, message = F, warning = F}

# Final regression model for the study
mod <- lm(perc_voted_no ~ log_n_shots_summer + vap_perc_white, 
          data = mpls_precincts_shots %>% 
            mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
            mutate(log_n_shots_summer = log(n_shots_summer)))

stargazer(mod, type = "text")
stargazer(mod, type = "html", out = "images/regression.html",
          covariate.labels = c("Log summer gunshots", "Voting age % white"),
          dep.var.labels   = "% voted \"no\" on Question 2")

```


```{r, message = F, warning = F}

# Regression experiment - turnout as an interaction variable with log summer gunshots
mod <- lm(perc_voted_no ~ log_n_shots_summer*turnout, 
          data = mpls_precincts_shots %>% 
            mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
            mutate(log_n_shots_summer = log(n_shots_summer)))

stargazer(mod, type = "text")

# Regression experiment - turnout as an additional variable with final model
mod <- lm(perc_voted_no ~ vap_perc_white + n_shots_summer + turnout, 
          data = mpls_precincts_shots %>% 
            mutate(n_shots_summer = ifelse(n_shots_summer > 80, 80, n_shots_summer)))

stargazer(mod, type = "text")

```


```{r, message = F, warning = F}

# Regression experiment - final model excluding University precincts
mod <- lm(perc_voted_no ~ log_n_shots_summer + vap_perc_white, 
          data = mpls_precincts_shots %>% 
            mutate(n_shots_summer = ifelse(n_shots_summer == 0, 1, n_shots_summer)) %>% 
            mutate(log_n_shots_summer = log(n_shots_summer)) %>% 
            filter(!precinct_name %in% c("W-2 P-4", "W-2 P-10")))

stargazer(mod, type = "text")

```












